### ISSUE TITLE
Support for tvOS

### ISSUE THREAD

**Issue by davidattias** [SBJson/SBJson#249]
I'm writing an app for tvOS and I would like to use your library but it is not declared to be compatible with tvOS in the podspec.

Is it compatible ?

Thanks

**Comment by stig** [comment]
I see no reason why it shouldn't be; tvOS just didn't exist when the podspec was created! Can you try making your own local podspec and see, and if you're successful report back with details so I can add it to the main podspec?

**Comment by davidattias** [comment]
ok thanks, I will try.

**Comment by stig** [comment]
@davidattias did you get anywhere with tvOS?

**Comment by davidattias** [comment]
Nope. I didn’t. You can close the issue as far as I’m concerned.

**Comment by stig** [comment]
Sorry it didn't work out. Thanks for confirming I can close though!
